### PR TITLE
MNT: Re-rendered

### PR DESCRIPTION
**Pull request by jcb91**

### CODE REVIEW

**Comment by jcb91** [comment]
bleagh, need to rerender [conda-forge/jupyter_latex_envs-feedstock](https://github.com/conda-forge/jupyter_latex_envs-feedstock) first

**Comment by jakirkham** [comment]
Also please make sure you have `conda-smithy` version `1.7.0` installed.

**Comment by jcb91** [comment]
@jakirkham right, ok. I'd been missing it by doing a simple 

    conda update conda-smithy

which doesn't do anything for me, but, on issuing

    conda install "conda-smithy>1.6"

I find that apparently, installing 1.7 was incompatible with `conda` 4.2 and `conda-env` 2.6, which I had to downgrade as a result...

**Comment by jakirkham** [comment]
Yeah, it actually always has been incompatible with `conda` 4.2. We only discovered it later. I think I may have fixed some issues in PR ( https://github.com/conda-forge/conda-smithy/pull/394 ), but am waiting for a review.

**Comment by jcb91** [comment]
Ok, I'm sorry this is getting so involved, but I'm having issues with the dependency [`jupyter_highlight_selected_word`'s feedstock](https://github.com/conda-forge/jupyter_highlight_selected_word-feedstock). Although the appveyor & circle builds compete ok, they don't upload to anaconda cloud (see builds https://circleci.com/gh/conda-forge/jupyter_highlight_selected_word-feedstock/5 and ). The circle build says 

    No BINSTAR_TOKEN present, so no upload is taking place.

but, according to https://circleci.com/gh/conda-forge/jupyter_highlight_selected_word-feedstock/edit#env-vars, the `BINSTAR_TOKEN` variable _is_ set 😕

**Comment by jcb91** [comment]
Also, the travis build [seems to have uploaded ok](https://travis-ci.org/conda-forge/jupyter_highlight_selected_word-feedstock/jobs/189473911#L610)

**Comment by jcb91** [comment]
ok, https://github.com/jcb91/jupyter_highlight_selected_word has uploaded ok following an update. I'll nudge this

**Pull request merged**
