### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by jcb91**
also attempting to use noarch: python, let's see how that goes :fearful:

### CODE REVIEW

**Comment by jakirkham** [comment]
Looks like pre/post-[un]link scripts may be incompatible with `noarch` unfortunately. This is a good data point though. Issue ( https://github.com/conda/conda-build/issues/2401 ) appears to be potentially related.

**Comment by jcb91** [comment]
yep, I seem to get permission-denied errors from the post-link script which is supposed to be editing/creating config files. I guess it makes sense, since we need separate scripts for Windows anyway :disappointed:

**Comment by jakirkham** [comment]
Not that it matters any more for this case, but when adding `noarch: python` one needs to re-render as well. FWIW we have some [commands]( https://conda-forge.org/docs/webservice.html ) to ask bots to do this for us if we don't want to try locally.

**Comment by jcb91** [comment]
> one needs to re-render as well

Ah, ok, thanks for the info!

**Pull request merged**
