### PR TITLE
update to version 0.3.2

### PR DESCRIPTION
**Pull request by jcb91**

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jakirkham** [comment]
Not sure whether this would work for you or not, but would take a look at [`noarch: python`]( http://conda-forge.readthedocs.io/en/latest/meta.html#building-noarch-packages ). If everything is in `site-packages`, this should work well, but would recommend trying a build locally. If not, we will probably need to wait for `conda-build` 3 to get this feature ( https://github.com/conda/conda-build/pull/2420 ).

**Comment by jcb91** [comment]
ah, apologies @jakirkham for the delay, I've only just noticed this thread!

> If everything is in `site-packages`, this should work well

Hmm, not sure about this. The pip package is all in `site-packeges`, and we've no data-files, but a bunch of stuff outside of site-packages gets edited/created as part of the post-link script. Does that (post-link stuff) preclude use of `noarch: python`?

**Comment by jakirkham** [comment]
No worries. Not pressing. Just thought you might be interested.

I think that should still be ok. Though would recommend testing it.

Not sure about whether [pre/post]-[un]link scripts work with `noarch`. @msarahan and/or @jjhelmus, could you please let us know whether these scripts will work with `noarch`?

**Pull request merged**
